---
- hosts: aci
  gather_facts: False
  connection: local
  vars_prompt:
    - name: var_vpc #variable
      private: no
      prompt: "Enter vpc name"

  tasks:
  - name: Create a Port Channel (PC) Interface Policy Group
    cisco.aci.aci_interface_policy_leaf_policy_group:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      lag_type: node
      policy_group: '{{ var_vpc }}'
      description: vPC_LAB_Creation
      link_level_policy: 10G_Auto
      cdp_policy: CDP_Enabled
      lldp_policy: LLDP_Enabled
      mcp_policy: MCP_DISABLE
      port_channel_policy: LACP_Enabled
      storm_control_interface_policy: STORM_ON
      stp_interface_policy: STP_ON
      state: present
      aep: AAEP-1
  - name: Create and Bind Access Port Selector with VPC Policy Group
    cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      interface_profile: leafsol
      access_port_selector: accessportselectorname
      policy_group: '{{ var_vpc }}'
      access_port_selector_name: anstest_vpc_accessportselector
      interface_type: vpc
      port_blk: leafportblkname
      from_port: 13
      to_port: 13
      state: present
