---
- hosts: aci
  gather_facts: False
  connection: local
  vars_prompt:
    - name: var_l3out #variable
      private: no
      prompt: "Enter Prod L3out" 
    - name: var_node_profile #variable
      private: no
      prompt: "Enter LNP Name" 
    - name: var_interface_profile #variable
      private: no
      prompt: "Enter Interface Profile Name" 
    - name: var_ext_epg1 #variable
      private: no
      prompt: "EXT-EPG1" 
    - name: var_ext_epg2 #variable
      private: no
      prompt: "EXT-EPG2"   
      
  tasks:
  - name: Create new Tenant
    cisco.aci.aci_tenant:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      description: 
      state: present
  - name: Create PHY DOMAIN
    cisco.aci.aci_domain:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      domain: L3DOM_INFRA
      domain_type: phys
      state: present
  - name: Create new VRFs1
    cisco.aci.aci_vrf:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      vrf: VRF_PRE_MAPFRE_FRONTALES
      tenant: PRE
      descr: Lab VRF
      policy_control_preference: enforced
      policy_control_direction: ingress
      state: present
  - name: Add a new L3Out
    cisco.aci.aci_l3out:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      route_control: export
      name: '{{ var_l3out }}'
      description: L3Out for Production tenant
      domain: L3DOM_INFRA
      vrf: VRF_PRE_MAPFRE_FRONTALES
      l3protocol: static
      state: present
  - name: Add a new node profile
    cisco.aci.aci_l3out_logical_node_profile:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      node_profile: '{{ var_node_profile }}'
      description: node profile for my_l3out
      l3out: '{{ var_l3out }}'
      tenant: PRE
      dscp: CS0
      state: present
  - name: Add a new interface profile
    cisco.aci.aci_l3out_logical_interface_profile:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      interface_profile: '{{ var_interface_profile }}'
      state: present
  - name: Deploy Logical Node_TO_CORE1 
    cisco.aci.aci_l3out_logical_node:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      pod_id: 1
      node_id: 1101
      router_id: 10.224.64.79
      state: present
  - name: Deploy Logical Nodes_TO_CORE2
    cisco.aci.aci_l3out_logical_node:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      pod_id: 1
      node_id: 1102
      router_id: 10.224.64.80
      state: present
  - name: Deploy Logical Nodes_TO_CORE3
    cisco.aci.aci_l3out_logical_node:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      pod_id: 2
      node_id: 2101
      router_id: 10.225.64.79
      state: present
  - name: Deploy Logical Nodes_TO_CORE4
    cisco.aci.aci_l3out_logical_node:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      pod_id: 2
      node_id: 2102
      router_id: 10.225.64.80
      state: present
  - name: Add a new SVI vPC
    cisco.aci.aci_l3out_interface:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      interface_profile: '{{ var_interface_profile }}'
      pod_id: 1
      node_id: 1101-1102
      path_ep: vPC_TO_NEW_F5_INTERNAL_PRE_NODO1
      interface_type: ext-svi
      encap: vlan-434
      mode: regular
      state: present
  - name: Add a new SVI vPC
    cisco.aci.aci_l3out_interface:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      interface_profile: '{{ var_interface_profile }}'
      pod_id: 2
      node_id: 2101-2102
      path_ep: vPC_TO_NEW_F5_INTERNAL_PRE_NODO2
      interface_type: ext-svi
      encap: vlan-434
      mode: regular
      state: present    
  - name: Create a VPC member based pod, node and path
    cisco.aci.aci_l3out_logical_interface_vpc_member:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      interface_profile: '{{ var_interface_profile }}'
      pod_id: 1
      node_id: 1101-1102
      path_ep: vPC_TO_NEW_F5_INTERNAL_PRE_NODO1
      side: A
      address: 10.224.80.34/28
      state: present
  - name: Create a VPC member based pod, node and path
    cisco.aci.aci_l3out_logical_interface_vpc_member:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      interface_profile: '{{ var_interface_profile }}'
      pod_id: 1
      node_id: 1101-1102
      path_ep: vPC_TO_NEW_F5_INTERNAL_PRE_NODO1
      side: B
      address: 10.224.80.35/28
      state: present
  - name: Add a new secondary IP to a vPC member
    cisco.aci.aci_l3out_interface_secondary_ip:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      interface_profile: '{{ var_interface_profile }}'
      pod_id: 1
      node_id: 1101-1102
      path_ep: vPC_TO_NEW_F5_INTERNAL_PRE_NODO1
      side: A
      address: 10.224.80.33/28
      side: B
      address: 10.224.80.33/28
      state: present
  - name: Create a VPC member based pod, node and path
    cisco.aci.aci_l3out_logical_interface_vpc_member:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      interface_profile: '{{ var_interface_profile }}'
      pod_id: 2
      node_id: 2101-2102
      path_ep: vPC_TO_NEW_F5_INTERNAL_PRE_NODO2
      side: A
      address: 10.224.80.36/28
      state: present
  - name: Create a VPC member based pod, node and path
    cisco.aci.aci_l3out_logical_interface_vpc_member:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      interface_profile: '{{ var_interface_profile }}'
      pod_id: 2
      node_id: 2101-2102
      path_ep: vPC_TO_NEW_F5_INTERNAL_PRE_NODO2
      side: B
      address: 10.224.80.37/28
      state: present
  - name: Add a new secondary IP to a vPC member
    cisco.aci.aci_l3out_interface_secondary_ip:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      interface_profile: '{{ var_interface_profile }}'
      pod_id: 2
      node_id: 2101-2102
      path_ep: vPC_TO_NEW_F5_INTERNAL_PRE_NODO2
      side: A
      address: 10.224.80.33/28
      side: B
      address: 10.224.80.33/28
      state: present
  - name: Create static routes
    cisco.aci.aci_l3out_static_routes:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      node_id: 1101
      pod_id: 1
      prefix: 10.231.113.0/24
  - name: Add a new nexthop to a prefix
    cisco.aci.aci_l3out_static_routes_nexthop:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      pod_id: 1
      node_id: 1101
      prefix: 10.231.113.0/24
      nexthop: 10.224.80.46
      state: present
  - name: Create static routes
    cisco.aci.aci_l3out_static_routes:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      node_id: 1102
      pod_id: 1
      prefix: 10.231.113.0/24
  - name: Add a new nexthop to a prefix
    cisco.aci.aci_l3out_static_routes_nexthop:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      pod_id: 1
      node_id: 1102
      prefix: 10.231.113.0/24
      nexthop: 10.224.80.46
      state: present
  - name: Create static routes
    cisco.aci.aci_l3out_static_routes:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      node_id: 2101
      pod_id: 2
      prefix: 10.231.113.0/24
  - name: Add a new nexthop to a prefix
    cisco.aci.aci_l3out_static_routes_nexthop:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      pod_id: 2
      node_id: 2101
      prefix: 10.231.113.0/24
      nexthop: 10.224.80.46
      state: present
  - name: Create static routes
    cisco.aci.aci_l3out_static_routes:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      node_id: 2102
      pod_id: 2
      prefix: 10.231.113.0/24
  - name: Add a new nexthop to a prefix
    cisco.aci.aci_l3out_static_routes_nexthop:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      node_profile: '{{ var_node_profile }}'
      pod_id: 2
      node_id: 2102
      prefix: 10.231.113.0/24
      nexthop: 10.224.80.46
      state: present
  - name: Add a new ExtEpg
    cisco.aci.aci_l3out_extepg:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      name: '{{ var_ext_epg1 }}'
      description: ExtEpg for Production L3Out
      state: present
  - name: Add a new External Subnet
    cisco.aci.aci_l3out_extsubnet:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      extepg: '{{ var_ext_epg1 }}'
      description: External Subnet for Production ExtEpg
      network: 0.0.0.0/0
      scope: export-rtctrl
      aggregate: export-rtctrl
      state: present
  - name: Bind a contract to an external EPG
    cisco.aci.aci_l3out_extepg_to_contract:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      extepg : '{{ var_ext_epg1 }}'
      contract: CTRT_PRE_F5-MAPFRE_FRONTALES
      contract_type: provider
      state: present
  - name: Bind a contract to an external EPG
    cisco.aci.aci_l3out_extepg_to_contract:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      extepg : '{{ var_ext_epg1 }}'
      contract: CTRT_PRE_TRANSITO_MAPFRE_FRONTALES
      contract_type: consumer
      state: present    
  - name: Add a new ExtEpg
    cisco.aci.aci_l3out_extepg:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      name: '{{ var_ext_epg2 }}'
      description: ExtEpg for Production L3Out
      state: present
  - name: Add a new External Subnet
    cisco.aci.aci_l3out_extsubnet:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      extepg: '{{ var_ext_epg2 }}'
      description: External Subnet for Production ExtEpg
      network: 0.0.0.0/0
      scope: export-rtctrl
      aggregate: export-rtctrl
      state: present
  - name: Bind a contract to an external EPG
    cisco.aci.aci_l3out_extepg_to_contract:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: PRE
      l3out: '{{ var_l3out }}'
      extepg : '{{ var_ext_epg2 }}'
      contract: CTRT_PRE_F5_MAPFRE-FRONTALES_VIP
      contract_type: provider
      state: present  