- hosts: aci
  gather_facts: False
  connection: local
  vars_prompt:
    - name: var_tenant #variable
      private: no
      prompt: "Enter Tenant name"
    - name: var_vrf1 #variable
      private: no
      prompt: "Enter VRF1 name"
    - name: var_l3out_name #variable
      private: no
      prompt: "Enter l3out name"
    - name: var_l3out_domain #variable
      private: no
      prompt: "Enter l3out domain"
    - name: var_l3out_vrf #variable
      private: no
      prompt: "Enter l3out vrf"
    - name: var_l3out_protocol #variable
      private: no
      prompt: "Enter l3out Routing protocol"
    - name: var_l3out_node_profile #variable
      private: no
      prompt: "Enter Node Profile"
    - name: var_l3out_interface_profile #variable
      private: no
      prompt: "Enter Interface Profile 1"
    - name: var_l3out_pod_id #variable
      private: no
      prompt: "Enter pod id"
    - name: var_l3out_node_id #variable
      private: no
      prompt: "Enter node id"
    - name: var_l3out_path_ep #variable
      private: no
      prompt: "Enter physical interface"
    - name: var_l3out_ipaddress #variable
      private: no
      prompt: "Enter svi ip address"

  tasks:
  - name: Create new Tenant
    cisco.aci.aci_tenant:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: '{{ var_tenant }}'
      description: 
      state: present
  - name: Create new VRFs1
    cisco.aci.aci_vrf:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      vrf: '{{ var_vrf1 }}'
      tenant: '{{ var_tenant }}'
      descr: Lab VRF
      policy_control_preference: enforced
      policy_control_direction: ingress
      state: present      
  - name: Add a new L3Out
    cisco.aci.aci_l3out:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      validate_certs: no
      tenant: '{{ var_tenant }}'
      name: '{{ var_l3out_name }}'
      description: L3Out for Production tenant
      domain: '{{ var_l3out_domain }}'
      vrf: '{{ var_l3out_vrf }}'
      l3protocol: '{{ var_l3out_protocol }}'
      route_control: export
      state: present
  - name: Add a new routed interface 1
    cisco.aci.aci_l3out_interface:
      host: '{{ apic }}'
      username: '{{ apic_user }}'
      password: '{{ apic_password }}'
      tenant: '{{ var_tenant }}'
      validate_certs: no
      l3out: '{{ var_l3out_name }}'
      node_profile: '{{ var_l3out_node_profile }}'
      interface_profile: '{{ var_l3out_interface_profile }}'
      pod_id: '{{ var_l3out_pod_id }}'
      node_id: '{{ var_l3out_node_id }}'
      path_ep: '{{ var_l3out_path_ep }}'
      interface_type: l3-port
      address: '{{ var_l3out_ipaddress }}'
      state: present