- hosts: paloalto
  gather_facts: False
  connection: local
  tasks:
  - name: search for shared address object
    panos_object:
    ip_address: '{{ fw2 }}'
    username: '{{ paloalto_user }}'
    password: '{{ paloalto_password }}'
    operation: 'find'
    address: 'DevNet'